
# Gem::Specification for Ambitious-sphinx-0.1.0
# Originally generated by Echoe

Gem::Specification.new do |s|
  s.name = %q{ambitious-sphinx}
  s.version = "0.1.0"

  s.specification_version = 2 if s.respond_to? :specification_version=

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Your Name"]
  s.date = %q{2008-01-18}
  s.description = %q{An ambitious adapter for sphinx}
  s.email = %q{your@email.com}
  s.files = ["lib/ambition/adapters/ambitious_sphinx/base.rb", "lib/ambition/adapters/ambitious_sphinx/query.rb", "lib/ambition/adapters/ambitious_sphinx/select.rb", "lib/ambition/adapters/ambitious_sphinx/slice.rb", "lib/ambition/adapters/ambitious_sphinx/sort.rb", "lib/ambition/adapters/ambitious_sphinx.rb", "LICENSE", "README", "test/helper.rb", "test/select_test.rb", "test/slice_test.rb", "test/sort_test.rb", "Manifest", "ambitious-sphinx.gemspec"]
  s.has_rdoc = true
  s.homepage = %q{http://ambition.rubyforge.org/}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{ambition}
  s.rubygems_version = %q{1.0.0}
  s.summary = %q{An ambitious adapter for sphinx}
  s.test_files = ["test/select_test.rb", "test/slice_test.rb", "test/sort_test.rb"]

  s.add_dependency(%q<ambition>, [">= 0.5.0"])
end


# # Original Rakefile source (requires the Echoe gem):
# 
# require 'rake'
# 
# Version = '0.1.0'
# 
# begin
#   require 'rubygems'
#   gem 'echoe', '>=2.7'
#   ENV['RUBY_FLAGS'] = ""
#   require 'echoe'
# 
#   Echoe.new('ambitious-sphinx') do |p|
#     # p.dependencies  << '<%= adapter_name %> >=1.0'
#     p.summary        = "An ambitious adapter for sphinx"
#     p.author         = 'Your Name'
#     p.email          = "your@email.com"
# 
#     p.project        = 'ambition'
#     p.url            = "http://ambition.rubyforge.org/"
#     p.test_pattern   = 'test/*_test.rb'
#     p.version        = Version
#     p.dependencies  << 'ambition >=0.5.0'
#   end
# 
# rescue LoadError 
#   puts "Not doing any of the Echoe gemmy stuff, because you don't have the specified gem versions"
# end
# 
# desc 'Install as a gem'
# task :install_gem do
#   puts `rake manifest package && gem install pkg/ambitious-sphinx-#{Version}.gem`
# end
